Composite primary key
EBIvariation/eva-seqcol pull request #6
Opened 2023-07-04 12:32 UTC by waterflow80

Made a composite primary key composed of both the **digest** and **naming_convention**.
In this way, we can add multiple seqcol objects that hold the same information, thus the **same digest L0**, but having different naming conventions.

2023-07-06 23:52 UTC, waterflow80 commented
I had a little problem while rebasing this branch, this is why the commit history looks a little bit ugly.
Sorry.

2023-07-07 09:24 UTC, tcezard requested changes

2023-07-07 09:24 UTC, tcezard commented on src/main/java/uk/ac/ebi/eva/evaseqcol/refget/SHA512Calculator.java
> +        return textHash.toLowerCase();
Why are you reverting back to returning the Hex string ?

2023-07-07 09:34 UTC, tcezard approved these changes

2023-07-07 09:35 UTC, waterflow80 commented
Sorry Tim, my bad.
I just fixed it.

2023-07-07 09:54 UTC, apriltuesday approved these changes

2023-07-07 20:35 UTC, sundarvenkata-EBI approved these changes

2023-07-08 10:32 UTC, merged